### ISSUE TITLE
SDP Message parser may fail to fetch media sections

### ISSUE THREAD

**Issue by SergeyVolokh** [diffblue/mjsip#1]
https://github.com/diffblue/mjsip/blob/f0ce4a24fceb3de52aa76220bff7385207cb9b67/src/main/java/org/mjsip/sdp/SdpMessage.java#L171

If bandwidth property is defined for specific media, it's going to be picked up as a part of the message header.
And it makes SdpParser.index to skip several lines including start of media section(s).
So, further results of parsing are invalid.

Sample data:
```
v=0
o=- 0268442511 0 IN IP4 192.168.1.108
s=phone-call
c=IN IP4 192.168.1.108
t=0 0
m=audio 20308 RTP/AVP 0 101
a=rtpmap:0 pcmu/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendonly
m=audio 20310 RTP/AVP 8 101
b=TIAS:64000
a=rtpmap:8 pcma/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendonly
```

RFC allows 'b' in media descriptions: https://www.rfc-editor.org/rfc/rfc2327

Thanks
WBR, Sergii

**Comment by ThomasPerkins1123** [comment]
Hi,
Thanks for showing an interest, however we are not the maintainers of this project. This is simply a repository created from the project http://www.mjsip.org/index.html, which was created for demo purposes. To avoid any confusion we are going to remove this repository.
Thanks
